import { PropsWithChildren } from 'react';

export const metadata = {
	description: 'Generated by create-nx-workspace',
	title: 'Welcome to root'
};

export default function RootLayout({ children }: PropsWithChildren): JSX.Element
{
	return (
		<html lang='en'>
			<body>{children}</body>
		</html>
	);
}