import { ReactNode } from 'react';

export const metadata = {
	description: 'Generated by create-nx-workspace',
	title: 'Welcome to blog'
};

export default function RootLayout({ children }: {
  children: React.ReactNode;
}): ReactNode
{
	return (
		<html lang='en'>
			<body>{children}</body>
		</html>
	);
}