/**
 * 루트 레이아웃 app 컴포넌트
 *
 * @author RWB
 * @since 2023.08.19 Sat 01:40:15
 */

import RootTemplate from '@kapoo/template/global/RootTemplate';

import type { Metadata } from 'next';
import { PropsWithChildren, ReactNode } from 'react';
import './_layout.scss';

export const metadata: Metadata = {
	description: 'Generated by create next app',
	title: 'Create Next App'
};

export type RootLayoutProps = PropsWithChildren;

/**
 * 루트 레이아웃 app 컴포넌트 JSX 반환 메서드
 *
 * @param {RootLayoutProps} param0: RootLayoutProps 객체
 *
 * @returns {ReactNode} ReactNode
 */
export default function RootLayout({ children }: RootLayoutProps): ReactNode
{
	return (
		<html lang='ko'>
			<head>
				<script src='https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js' async />
			</head>

			<body>
				<RootTemplate>
					{children}
				</RootTemplate>
			</body>
		</html>
	);
}