# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    tags:
      - v*

jobs:
  set-dependencies:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-kapoo-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-kapoo

      - name: kapoo Dependencies Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install

  build:
    needs: set-dependencies
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Repository Checkout
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - uses: pnpm/action-setup@v4
      with:
        version: 8

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-kapoo-${{ hashFiles('yarn.lock') }}
        restore-keys: ${{ runner.os }}-kapoo

    - name: build root
      run: pnpm nx build root

    - name: build blog
      run: pnpm nx build blog

    - name: Pushes to itcode.dev Public Repository
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.TOKEN }}
      with:
        source-directory: apps/root/out
        destination-github-username: RWB0104
        destination-repository-name: itcode.dev
        user-email: psj2716@mensakorea.org
        target-branch: main
        target-directory: docs
        commit-message: ${{ github.event.head_commit.message }}

    - name: Pushes to blog.itcode.dev Public Repository
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.TOKEN }}
      with:
        source-directory: apps/blog/out
        destination-github-username: RWB0104
        destination-repository-name: blog.itcode.dev
        user-email: psj2716@mensakorea.org
        target-branch: master
        target-directory: docs
        commit-message: ${{ github.event.head_commit.message }}