# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Repository Checkout
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Dependencies Install
      run: yarn

    - name: Build SEO
      run: yarn seo

    - name: build
      run: yarn build

    - name: Pushes to itcode.dev Public Repository
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.TOKEN }}
      with:
        source-directory: out
        destination-github-username: RWB0104
        destination-repository-name: blog.itcode.dev
        user-email: psj2716@mensakorea.org
        target-branch: main
        target-directory: docs
        commit-message: ${{ github.event.head_commit.message }}
